version: "3.5"

networks:
  receiver:
    name: receiver

services:
  nats:
    image: nats
    restart: always
    ports:
      - "8222:8222"
      - "4222:4222"
    networks: ["receiver"]
  nats-1:
    image: nats
    restart: on-failure
    command: "--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["receiver"]
    depends_on: ["nats"]
  nats-2:
    image: nats
    restart: on-failure
    command: "--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["receiver"]
    depends_on: ["nats"]
  receiver:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.receiver
    restart: always
    ports:
      - "9001:9001"
    environment:
      TZ: Asia/Yekaterinburg
    networks: ["receiver"]
    depends_on: ["nats"]
  # saver:
  #   build:
  #     context: .
  #     dockerfile: ./docker/Dockerfile.saver
  #   restart: always
  #   environment:
  #     TZ: Asia/Yekaterinburg
  #   networks: ["receiver"]
  #   depends_on: ["nats"]
  saver:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.saver2
    environment:
      TZ: Asia/Yekaterinburg
    networks: ["receiver"]
    depends_on: ["nats"]
